//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscussionDesktop.srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srv.wsChatSoap")]
    public interface wsChatSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/exist", ReplyAction="*")]
        DiscussionDesktop.srv.existResponse exist(DiscussionDesktop.srv.existRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/exist", ReplyAction="*")]
        System.IAsyncResult Beginexist(DiscussionDesktop.srv.existRequest request, System.AsyncCallback callback, object asyncState);
        
        DiscussionDesktop.srv.existResponse Endexist(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément u de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        DiscussionDesktop.srv.addUserResponse addUser(DiscussionDesktop.srv.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.IAsyncResult BeginaddUser(DiscussionDesktop.srv.addUserRequest request, System.AsyncCallback callback, object asyncState);
        
        DiscussionDesktop.srv.addUserResponse EndaddUser(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getAllUsersResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllUsers", ReplyAction="*")]
        DiscussionDesktop.srv.getAllUsersResponse getAllUsers(DiscussionDesktop.srv.getAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getAllUsers", ReplyAction="*")]
        System.IAsyncResult BegingetAllUsers(DiscussionDesktop.srv.getAllUsersRequest request, System.AsyncCallback callback, object asyncState);
        
        DiscussionDesktop.srv.getAllUsersResponse EndgetAllUsers(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément u de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dropUser", ReplyAction="*")]
        DiscussionDesktop.srv.dropUserResponse dropUser(DiscussionDesktop.srv.dropUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/dropUser", ReplyAction="*")]
        System.IAsyncResult BegindropUser(DiscussionDesktop.srv.dropUserRequest request, System.AsyncCallback callback, object asyncState);
        
        DiscussionDesktop.srv.dropUserResponse EnddropUser(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class existRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exist", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.existRequestBody Body;
        
        public existRequest() {
        }
        
        public existRequest(DiscussionDesktop.srv.existRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class existRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public existRequestBody() {
        }
        
        public existRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class existResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="existResponse", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.existResponseBody Body;
        
        public existResponse() {
        }
        
        public existResponse(DiscussionDesktop.srv.existResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class existResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool existResult;
        
        public existResponseBody() {
        }
        
        public existResponseBody(bool existResult) {
            this.existResult = existResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(DiscussionDesktop.srv.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DiscussionDesktop.srv.User u;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(DiscussionDesktop.srv.User u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(DiscussionDesktop.srv.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addUserResponseBody {
        
        public addUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.getAllUsersRequestBody Body;
        
        public getAllUsersRequest() {
        }
        
        public getAllUsersRequest(DiscussionDesktop.srv.getAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllUsersRequestBody {
        
        public getAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.getAllUsersResponseBody Body;
        
        public getAllUsersResponse() {
        }
        
        public getAllUsersResponse(DiscussionDesktop.srv.getAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DiscussionDesktop.srv.User[] getAllUsersResult;
        
        public getAllUsersResponseBody() {
        }
        
        public getAllUsersResponseBody(DiscussionDesktop.srv.User[] getAllUsersResult) {
            this.getAllUsersResult = getAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dropUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dropUser", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.dropUserRequestBody Body;
        
        public dropUserRequest() {
        }
        
        public dropUserRequest(DiscussionDesktop.srv.dropUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dropUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DiscussionDesktop.srv.User u;
        
        public dropUserRequestBody() {
        }
        
        public dropUserRequestBody(DiscussionDesktop.srv.User u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dropUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dropUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DiscussionDesktop.srv.dropUserResponseBody Body;
        
        public dropUserResponse() {
        }
        
        public dropUserResponse(DiscussionDesktop.srv.dropUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dropUserResponseBody {
        
        public dropUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsChatSoapChannel : DiscussionDesktop.srv.wsChatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class existCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public existCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DiscussionDesktop.srv.User[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DiscussionDesktop.srv.User[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsChatSoapClient : System.ServiceModel.ClientBase<DiscussionDesktop.srv.wsChatSoap>, DiscussionDesktop.srv.wsChatSoap {
        
        private BeginOperationDelegate onBeginexistDelegate;
        
        private EndOperationDelegate onEndexistDelegate;
        
        private System.Threading.SendOrPostCallback onexistCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddUserDelegate;
        
        private EndOperationDelegate onEndaddUserDelegate;
        
        private System.Threading.SendOrPostCallback onaddUserCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllUsersDelegate;
        
        private EndOperationDelegate onEndgetAllUsersDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllUsersCompletedDelegate;
        
        private BeginOperationDelegate onBegindropUserDelegate;
        
        private EndOperationDelegate onEnddropUserDelegate;
        
        private System.Threading.SendOrPostCallback ondropUserCompletedDelegate;
        
        public wsChatSoapClient() {
        }
        
        public wsChatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsChatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsChatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsChatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<existCompletedEventArgs> existCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> addUserCompleted;
        
        public event System.EventHandler<getAllUsersCompletedEventArgs> getAllUsersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> dropUserCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.existResponse DiscussionDesktop.srv.wsChatSoap.exist(DiscussionDesktop.srv.existRequest request) {
            return base.Channel.exist(request);
        }
        
        public bool exist(string pseudo) {
            DiscussionDesktop.srv.existRequest inValue = new DiscussionDesktop.srv.existRequest();
            inValue.Body = new DiscussionDesktop.srv.existRequestBody();
            inValue.Body.pseudo = pseudo;
            DiscussionDesktop.srv.existResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).exist(inValue);
            return retVal.Body.existResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscussionDesktop.srv.wsChatSoap.Beginexist(DiscussionDesktop.srv.existRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginexist(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginexist(string pseudo, System.AsyncCallback callback, object asyncState) {
            DiscussionDesktop.srv.existRequest inValue = new DiscussionDesktop.srv.existRequest();
            inValue.Body = new DiscussionDesktop.srv.existRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((DiscussionDesktop.srv.wsChatSoap)(this)).Beginexist(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.existResponse DiscussionDesktop.srv.wsChatSoap.Endexist(System.IAsyncResult result) {
            return base.Channel.Endexist(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endexist(System.IAsyncResult result) {
            DiscussionDesktop.srv.existResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).Endexist(result);
            return retVal.Body.existResult;
        }
        
        private System.IAsyncResult OnBeginexist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo = ((string)(inValues[0]));
            return this.Beginexist(pseudo, callback, asyncState);
        }
        
        private object[] OnEndexist(System.IAsyncResult result) {
            bool retVal = this.Endexist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnexistCompleted(object state) {
            if ((this.existCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.existCompleted(this, new existCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void existAsync(string pseudo) {
            this.existAsync(pseudo, null);
        }
        
        public void existAsync(string pseudo, object userState) {
            if ((this.onBeginexistDelegate == null)) {
                this.onBeginexistDelegate = new BeginOperationDelegate(this.OnBeginexist);
            }
            if ((this.onEndexistDelegate == null)) {
                this.onEndexistDelegate = new EndOperationDelegate(this.OnEndexist);
            }
            if ((this.onexistCompletedDelegate == null)) {
                this.onexistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnexistCompleted);
            }
            base.InvokeAsync(this.onBeginexistDelegate, new object[] {
                        pseudo}, this.onEndexistDelegate, this.onexistCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.addUserResponse DiscussionDesktop.srv.wsChatSoap.addUser(DiscussionDesktop.srv.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public void addUser(DiscussionDesktop.srv.User u) {
            DiscussionDesktop.srv.addUserRequest inValue = new DiscussionDesktop.srv.addUserRequest();
            inValue.Body = new DiscussionDesktop.srv.addUserRequestBody();
            inValue.Body.u = u;
            DiscussionDesktop.srv.addUserResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).addUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscussionDesktop.srv.wsChatSoap.BeginaddUser(DiscussionDesktop.srv.addUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddUser(DiscussionDesktop.srv.User u, System.AsyncCallback callback, object asyncState) {
            DiscussionDesktop.srv.addUserRequest inValue = new DiscussionDesktop.srv.addUserRequest();
            inValue.Body = new DiscussionDesktop.srv.addUserRequestBody();
            inValue.Body.u = u;
            return ((DiscussionDesktop.srv.wsChatSoap)(this)).BeginaddUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.addUserResponse DiscussionDesktop.srv.wsChatSoap.EndaddUser(System.IAsyncResult result) {
            return base.Channel.EndaddUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndaddUser(System.IAsyncResult result) {
            DiscussionDesktop.srv.addUserResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).EndaddUser(result);
        }
        
        private System.IAsyncResult OnBeginaddUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            DiscussionDesktop.srv.User u = ((DiscussionDesktop.srv.User)(inValues[0]));
            return this.BeginaddUser(u, callback, asyncState);
        }
        
        private object[] OnEndaddUser(System.IAsyncResult result) {
            this.EndaddUser(result);
            return null;
        }
        
        private void OnaddUserCompleted(object state) {
            if ((this.addUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addUserAsync(DiscussionDesktop.srv.User u) {
            this.addUserAsync(u, null);
        }
        
        public void addUserAsync(DiscussionDesktop.srv.User u, object userState) {
            if ((this.onBeginaddUserDelegate == null)) {
                this.onBeginaddUserDelegate = new BeginOperationDelegate(this.OnBeginaddUser);
            }
            if ((this.onEndaddUserDelegate == null)) {
                this.onEndaddUserDelegate = new EndOperationDelegate(this.OnEndaddUser);
            }
            if ((this.onaddUserCompletedDelegate == null)) {
                this.onaddUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddUserCompleted);
            }
            base.InvokeAsync(this.onBeginaddUserDelegate, new object[] {
                        u}, this.onEndaddUserDelegate, this.onaddUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.getAllUsersResponse DiscussionDesktop.srv.wsChatSoap.getAllUsers(DiscussionDesktop.srv.getAllUsersRequest request) {
            return base.Channel.getAllUsers(request);
        }
        
        public DiscussionDesktop.srv.User[] getAllUsers() {
            DiscussionDesktop.srv.getAllUsersRequest inValue = new DiscussionDesktop.srv.getAllUsersRequest();
            inValue.Body = new DiscussionDesktop.srv.getAllUsersRequestBody();
            DiscussionDesktop.srv.getAllUsersResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).getAllUsers(inValue);
            return retVal.Body.getAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscussionDesktop.srv.wsChatSoap.BegingetAllUsers(DiscussionDesktop.srv.getAllUsersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAllUsers(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetAllUsers(System.AsyncCallback callback, object asyncState) {
            DiscussionDesktop.srv.getAllUsersRequest inValue = new DiscussionDesktop.srv.getAllUsersRequest();
            inValue.Body = new DiscussionDesktop.srv.getAllUsersRequestBody();
            return ((DiscussionDesktop.srv.wsChatSoap)(this)).BegingetAllUsers(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.getAllUsersResponse DiscussionDesktop.srv.wsChatSoap.EndgetAllUsers(System.IAsyncResult result) {
            return base.Channel.EndgetAllUsers(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public DiscussionDesktop.srv.User[] EndgetAllUsers(System.IAsyncResult result) {
            DiscussionDesktop.srv.getAllUsersResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).EndgetAllUsers(result);
            return retVal.Body.getAllUsersResult;
        }
        
        private System.IAsyncResult OnBegingetAllUsers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetAllUsers(callback, asyncState);
        }
        
        private object[] OnEndgetAllUsers(System.IAsyncResult result) {
            DiscussionDesktop.srv.User[] retVal = this.EndgetAllUsers(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllUsersCompleted(object state) {
            if ((this.getAllUsersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllUsersCompleted(this, new getAllUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllUsersAsync() {
            this.getAllUsersAsync(null);
        }
        
        public void getAllUsersAsync(object userState) {
            if ((this.onBegingetAllUsersDelegate == null)) {
                this.onBegingetAllUsersDelegate = new BeginOperationDelegate(this.OnBegingetAllUsers);
            }
            if ((this.onEndgetAllUsersDelegate == null)) {
                this.onEndgetAllUsersDelegate = new EndOperationDelegate(this.OnEndgetAllUsers);
            }
            if ((this.ongetAllUsersCompletedDelegate == null)) {
                this.ongetAllUsersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllUsersCompleted);
            }
            base.InvokeAsync(this.onBegingetAllUsersDelegate, null, this.onEndgetAllUsersDelegate, this.ongetAllUsersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.dropUserResponse DiscussionDesktop.srv.wsChatSoap.dropUser(DiscussionDesktop.srv.dropUserRequest request) {
            return base.Channel.dropUser(request);
        }
        
        public void dropUser(DiscussionDesktop.srv.User u) {
            DiscussionDesktop.srv.dropUserRequest inValue = new DiscussionDesktop.srv.dropUserRequest();
            inValue.Body = new DiscussionDesktop.srv.dropUserRequestBody();
            inValue.Body.u = u;
            DiscussionDesktop.srv.dropUserResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).dropUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscussionDesktop.srv.wsChatSoap.BegindropUser(DiscussionDesktop.srv.dropUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindropUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindropUser(DiscussionDesktop.srv.User u, System.AsyncCallback callback, object asyncState) {
            DiscussionDesktop.srv.dropUserRequest inValue = new DiscussionDesktop.srv.dropUserRequest();
            inValue.Body = new DiscussionDesktop.srv.dropUserRequestBody();
            inValue.Body.u = u;
            return ((DiscussionDesktop.srv.wsChatSoap)(this)).BegindropUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscussionDesktop.srv.dropUserResponse DiscussionDesktop.srv.wsChatSoap.EnddropUser(System.IAsyncResult result) {
            return base.Channel.EnddropUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EnddropUser(System.IAsyncResult result) {
            DiscussionDesktop.srv.dropUserResponse retVal = ((DiscussionDesktop.srv.wsChatSoap)(this)).EnddropUser(result);
        }
        
        private System.IAsyncResult OnBegindropUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            DiscussionDesktop.srv.User u = ((DiscussionDesktop.srv.User)(inValues[0]));
            return this.BegindropUser(u, callback, asyncState);
        }
        
        private object[] OnEnddropUser(System.IAsyncResult result) {
            this.EnddropUser(result);
            return null;
        }
        
        private void OndropUserCompleted(object state) {
            if ((this.dropUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.dropUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void dropUserAsync(DiscussionDesktop.srv.User u) {
            this.dropUserAsync(u, null);
        }
        
        public void dropUserAsync(DiscussionDesktop.srv.User u, object userState) {
            if ((this.onBegindropUserDelegate == null)) {
                this.onBegindropUserDelegate = new BeginOperationDelegate(this.OnBegindropUser);
            }
            if ((this.onEnddropUserDelegate == null)) {
                this.onEnddropUserDelegate = new EndOperationDelegate(this.OnEnddropUser);
            }
            if ((this.ondropUserCompletedDelegate == null)) {
                this.ondropUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndropUserCompleted);
            }
            base.InvokeAsync(this.onBegindropUserDelegate, new object[] {
                        u}, this.onEnddropUserDelegate, this.ondropUserCompletedDelegate, userState);
        }
    }
}
